AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  museepa

  Sample SAM Template for museepa

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  CrudEvents:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: crud_events/
      Handler: get_event.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /event
            Method: GET
      Environment:
        Variables:
          RDS_PROXY_HOST: !Ref RDSProxyHost
          USER_NAME: !Ref DBUserName
          PASSWORD: !Ref DBPassword
          DB_NAME: !Ref DBName

Parameters:
  RDSProxyHost:
    Type: String
    Description: 'El host del RDS Proxy'
  DBUserName:
    Type: String
    Description: 'El nombre de usuario de la base de datos'
  DBPassword:
    Type: String
    Description: 'La contraseña de la base de datos'
  DBName:
    Type: String
    Description: 'El nombre de la base de datos'

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  CrudEventApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/event/"
