AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  museepa

  Sample SAM Template for museepa

Globals:
  Function:
    Timeout: 3

Resources:

  EventApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: EventApi
      StageName: Dev

  MuseumApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MuseumApi
      StageName: Dev

  WorkApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: WorkApi
      StageName: Dev

  GetDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/get_events/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: GET
  CreateDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/create_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: POST
  DeleteDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/delete_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events/{id}
            Method: DELETE
  UpdateDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/update_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: PUT
  FindDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/find_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        FindEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events/{id}
            Method: GET

# ------------ Museum ------------
  GetDataMuseumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/museums/get_museums/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetMuseum:
          Type: Api
          Properties:
            RestApiId: !Ref MuseumApi
            Path: /museums
            Method: GET
  CreateDataMuseumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/museums/create_museum/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CreateMuseum:
          Type: Api
          Properties:
            RestApiId: !Ref MuseumApi
            Path: /museums
            Method: POST
  DeleteDataMuseumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/museums/delete_museum/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteMuseum:
          Type: Api
          Properties:
            RestApiId: !Ref MuseumApi
            Path: /museums/{id}
            Method: DELETE
  UpdateDataMuseumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/museums/update_museum/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdateMuseum:
          Type: Api
          Properties:
            RestApiId: !Ref MuseumApi
            Path: /museums
            Method: PUT
  FindDataMuseumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/museums/find_museum/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        FindMuseum:
          Type: Api
          Properties:
            RestApiId: !Ref MuseumApi
            Path: /museums/{id}
            Method: GET

# ------------ Work ------------
  GetDataWorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/works/get_works/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref WorkApi
            Path: /works
            Method: GET
  CreateDataWorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/works/create_work/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref WorkApi
            Path: /works
            Method: POST
  DeleteDataWorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/works/delete_work/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref WorkApi
            Path: /works/{id}
            Method: DELETE
  UpdateDataWorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/works/update_work/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref WorkApi
            Path: /works
            Method: PUT
  FindDataWorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/works/find_work/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        FindEvent:
          Type: Api
          Properties:
            RestApiId: !Ref WorkApi
            Path: /works/{id}
            Method: GET

Outputs:
    EventApi:
        Description: "API Gateway endpoint URL for Prod stage for museepa function"
        Value: !Sub "https://${EventApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    MuseumApi:
        Description: "API Gateway endpoint URL for Prod stage for museepa function"
        Value: !Sub "https://${MuseumApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    WorkApi:
      Description: "API Gateway endpoint URL for Prod stage for museepa function"
      Value: !Sub "https://${MuseumApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

