AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  museepa

  Sample SAM Template for museepa

Globals:
  Function:
    Timeout: 3

Resources:

  EventApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: EventApi
      StageName: Dev


  GetDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/get_events/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: GET
  CreateDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/create_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: POST
  DeleteDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/delete_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events/{id}
            Method: DELETE
  UpdateDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/update_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events
            Method: PUT
  FindDataEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/events/find_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        FindEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventApi
            Path: /events/{id}
            Method: GET




#  EventsApi:
#    Type: AWS::Serverless::Api
#    Properties:
#      Name: EventApi
#      StageName: Prod
#
#  AddEventFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: crud_events/
#      Handler: app.insert_event
#      Runtime: python3.12
#      Architectures:
#        - x86_64
#      Events:
#        CreateEvent:
#          Type: Api
#          Properties:
#            RestApiId: !Ref EventsApi
#            Path: /events
#            Method: POST
#
#  UpdateEventFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: crud_events/
#      Handler: app.update_event
#      Runtime: python3.12
#      Architectures:
#        - x86_64
#      Events:
#        UpdateEvent:
#          Type: Api
#          Properties:
#            RestApiId: !Ref EventsApi
#            Path: /events
#            Method: PUT
#
#  GetEventFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: crud_events/
#      Handler: app.get_event
#      Runtime: python3.12
#      Architectures:
#        - x86_64
#      Events:
#        GetEvent:
#          Type: Api
#          Properties:
#            RestApiId: !Ref EventsApi
#            Path: /events
#            Method: GET
#
#  DeleteEventFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: crud_events/
#      Handler: app.delete_event
#      Runtime: python3.12
#      Architectures:
#        - x86_64
#      Events:
#        DeleteEvent:
#          Type: Api
#          Properties:
#            RestApiId: !Ref EventsApi
#            Path: /events
#            Method: DELETE

Outputs:
    EventApi:
        Description: "API Gateway endpoint URL for Prod stage for museepa function"
        Value: !Sub "https://${EventApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

