[tox]
envlist = py39
skipsdist = True

[testenv]
deps =
    pytest
    coverage
commands =
    coverage run -m pytest
    coverage xml

[coverage:run]
relative_files = True
source = museepa
branch = True

[coverage:report]
# Opcional: incluye esta sección para personalizar la salida del informe de cobertura
omit =
    */tests/*
    */venv/*
    */migrations/*
